"""phase5 initial schema

Revision ID: 3ee520dc1b7a
Revises:
Create Date: 2026-07-16 16:22:01.370042
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '3ee520dc1b7a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('viewer', 'operator', 'admin')", name='ck_library_admins_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('library_import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('staged', 'validated', 'approved', 'applied', 'rejected')", name='ck_library_import_batches_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash')
    )
    op.create_table('library_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('normalized_student_number', sa.String(length=16), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('academic_role', sa.String(length=32), nullable=False),
    sa.Column('faculty_code', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('member_status', sa.String(length=32), nullable=False),
    sa.Column('record_version', sa.BigInteger(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("member_status IN ('active', 'pending_review', 'inactive')", name='ck_library_members_status'),
    sa.CheckConstraint('normalized_email = lower(normalized_email)', name='ck_library_members_email_normalized'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_members_normalized_email'), ['normalized_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_library_members_normalized_student_number'), ['normalized_student_number'], unique=True)

    op.create_table('library_access_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('permission_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'granted', 'already_granted', 'failed', 'revoked')", name='ck_library_access_grants_status'),
    sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'resource_id', name='uq_library_access_grants_member_resource'),
    sa.UniqueConstraint('permission_id')
    )
    with op.batch_alter_table('library_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_access_grants_member_id'), ['member_id'], unique=False)

    op.create_table('library_admin_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['library_admins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_admin_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_admin_audit_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_admin_audit_member_id'), ['member_id'], unique=False)

    op.create_table('library_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('normalized_student_number', sa.String(length=16), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('academic_role', sa.String(length=32), nullable=False),
    sa.Column('faculty_code', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=32), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('terms_version', sa.String(length=64), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_version', sa.String(length=64), nullable=True),
    sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("eligibility_status IN ('approved', 'manual_review', 'ineligible', 'already_registered')", name='ck_library_applications_status'),
    sa.CheckConstraint('normalized_email = lower(normalized_email)', name='ck_library_applications_email_normalized'),
    sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('library_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_applications_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_applications_normalized_email'), ['normalized_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_applications_normalized_student_number'), ['normalized_student_number'], unique=False)

    op.create_table('library_export_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['library_admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_export_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_export_runs_admin_id'), ['admin_id'], unique=False)

    op.create_table('library_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('verified_email', sa.String(length=320), nullable=False),
    sa.Column('hosted_domain', sa.String(length=255), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('verified_email = lower(verified_email)', name='ck_library_identities_email_normalized'),
    sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    with op.batch_alter_table('library_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_identities_member_id'), ['member_id'], unique=False)

    op.create_table('library_import_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('error_codes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['library_import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'source_row_number', name='uq_library_import_rows_batch_row')
    )
    with op.batch_alter_table('library_import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_import_rows_batch_id'), ['batch_id'], unique=False)

    op.create_table('library_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('operation_key', sa.String(length=255), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'dead')", name='ck_library_operations_status'),
    sa.ForeignKeyConstraint(['application_id'], ['library_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_key')
    )
    with op.batch_alter_table('library_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_operations_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_operations_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_operations_member_id'))
        batch_op.drop_index(batch_op.f('ix_library_operations_application_id'))

    op.drop_table('library_operations')
    with op.batch_alter_table('library_import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_import_rows_batch_id'))

    op.drop_table('library_import_rows')
    with op.batch_alter_table('library_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_identities_member_id'))

    op.drop_table('library_identities')
    with op.batch_alter_table('library_export_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_export_runs_admin_id'))

    op.drop_table('library_export_runs')
    with op.batch_alter_table('library_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_applications_normalized_student_number'))
        batch_op.drop_index(batch_op.f('ix_library_applications_normalized_email'))
        batch_op.drop_index(batch_op.f('ix_library_applications_member_id'))

    op.drop_table('library_applications')
    with op.batch_alter_table('library_admin_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_admin_audit_member_id'))
        batch_op.drop_index(batch_op.f('ix_library_admin_audit_admin_id'))

    op.drop_table('library_admin_audit')
    with op.batch_alter_table('library_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_access_grants_member_id'))

    op.drop_table('library_access_grants')
    with op.batch_alter_table('library_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_members_normalized_student_number'))
        batch_op.drop_index(batch_op.f('ix_library_members_normalized_email'))

    op.drop_table('library_members')
    op.drop_table('library_import_batches')
    op.drop_table('library_admins')
    # ### end Alembic commands ###
